### ISSUE TITLE
Slightly more detailed build documentation?

### ISSUE THREAD

**Issue by grzesiek-galezowski** [wasteddesign/ReBuzz#16]
Hi, I want to start digging into the code to see if I can be of any help. While I can build the code in this repo, it doesn't launch. I can see that the "How to build" section in the README says to update the references to assemblies in the installer, but I couldn't find any installer. Also, I can see there are three repositories in total and probably all of them are necessary to build the full app. Could you offer some more pointers as how to make all of this work together to be able to debug something?

**Comment by HerrFornit** [comment]
perhaps it is not what you look for, but the installer I know is here:
https://buzz.robotplanet.dk/files/ReBuzzSetup_2024_Preview.exe
(s. "code" start page here)

**Comment by themarcnet** [comment]
Agreed. All I want to do is add wavetable support. I have a plan on how to do so, but the current source layout at the moment is a bit scattered.  

My plan is to use a CLR DLL to implement all the wavetable stuff.  CLR is basically C++ that C# can use the types from, and directly call the methods of.  I have done this before with other C#/c++ projects, and it would be ideal for use on ReBuzz.

But at the moment I have no idea how to build ReBuzz, and what repos to install and where to install them!

Ideally I would want a single solution file that has all the required projects/modules loaded into a single instance of Visual Studio, where all the dependencies/references are already set up.  This structure would also include my CLR dll for doing wavetable stuff. Also, ideally, all the projects are located in a single repo - not 12 (or however many - it's very unclear what repos to download)

**Comment by themarcnet** [comment]
I'm in the middle of making a solution file that will contain everything - 3rd party dependencies, the repos from here and, of course, rebuzz itself.   The idea is to use github submodules to reference all the rebuzz stuff and dependencies so it can be cloned and built in one easy (well, two) step(s)

The 7zip SDK is required (https://7-zip.org/sdk.html), which I'm building as a separate .NET Framework 4.7.2 class library, and therefore some 'using RangeCoder' in the rebuzz code needs to be changed to 'using SevenZip.Compression.RangeCoder' - since I presume ReBuzz was originally built with the sdk directly integrated into the ReBuzz source tree.  

(It's usually a good idea to separate your code from 3rd party code, which is what I've done here)

However, I'm missing 'ModernSequenceEditor.Interfaces' - it does not seem to be in any of your repos, and it probably isn't a 3rd party reference.  Does anyone know where this reference is located?  

Also: I'm on the Buzz discord if you want a more real-time chat with myself.

**Comment by wasteddesign** [comment]
> Hi, I want to start digging into the code to see if I can be of any help. While I can build the code in this repo, it doesn't launch. I can see that the "How to build" section in the README says to update the references to assemblies in the installer, but I couldn't find any installer. Also, I can see there are three repositories in total and probably all of them are necessary to build the full app. Could you offer some more pointers as how to make all of this work together to be able to debug something?

Thanks for your upcoming improvements! I added few steps to the readme that should make building easier using Visual Studio.

**Comment by wasteddesign** [comment]
> My plan is to use a CLR DLL to implement all the wavetable stuff. CLR is basically C++ that C# can use the types from, and directly call the methods of. I have done this before with other C#/c++ projects, and it would be ideal for use on ReBuzz.

Looking forward to that! I pushed some wave handling improvements and cleanups. There are now initial building blocks to make wavetable work for native machines. You need latest ReBuzzEngine changes and comment [return line](https://github.com/wasteddesign/ReBuzz/blob/86aff5e7354e682417a9d90c754a828fbecf20dc/ReBuzz/NativeMachine/AudioMessage.cs#L218C4-L218C5) to start debugging.

**Comment by grzesiek-galezowski** [comment]
Hi, I'll close this one as there is a more detailed build and debug procedure which I was able to follow.
